### ISSUE TITLE
Forward port to Rust 1.62

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android-Backend#168] opened 2022-04-07 20:11 UTC
Using current rust (currently 1.62) should be possible but we specify 1.58.1 everywhere

to test

```bash
rustup install 1.62.0
rustup default 1.62.0
```

Then make sure you have the cross compilers installed for the android architectures for this version:

```bash
rustup target add armv7-linux-androideabi
rustup target add i686-linux-android
rustup target add aarch64-linux-android
rustup target add x86_64-linux-android
```

should work? just needs testing then updates of doctor + docs + workflows

**Comment by mikehardy** [comment] 2022-04-07 20:34
cross hasn't released since 2020 (v0.2.1) but has current development, just untagged? Anyway if you use cargo to install cross via git ref, by default it uses tip of default branch which requires cargo with edition 2021 at least

If you pin the cargo install of cross via git to a tag of v0.2.1 it works - also documenting that

entropy!

**Comment by david-allison** [comment] 2022-04-07 21:16
It's very likely that we'll be able to update the underlying Anki library and get this for free.

I'd rather focus on a fixed target: 2.1.35 works in dev (only one concern with syncing). Once we get that released, we can move to 2.1.49 and it should compile under the latest Rust version

**Comment by mikehardy** [comment] 2022-04-08 03:15
Perfect. Back-burner on this one then since it does seem to be an rslib problem, we should get it "for free", and what we have now works fine (and is documented! or will be, plus supported by doctor). This can track it just in case though

**Comment by dae** [comment] 2022-06-30 06:35
This can be closed

**Comment by mikehardy** [comment] 2022-06-30 13:02
Not until I see the dependency bump actually in and it passes CI everywhere :smiling_imp: - right now doctor and workflows and docs are all saying+using 1.58.1 so there is no demonstrated success

Really, it should say 1.62.0 now anyway as that's current and the idea is to either get current or track why not

**Comment by dae** [comment] 2022-06-30 23:25
The current code should work fine on the latest Rust, but I used 1.58.1 because that's what the desktop is currently pinned to - there was a compile speed regression at one point that required the pin, though presumably that's been fixed now.

**Closed** 2022-12-16 18:53 UTC
Labels: bug, dependencies
